# Generated by Django 4.1 on 2022-08-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='integer_example',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
